@startuml
title Usecase for Information system
left to right direction

actor Співачка_споживач
actor Світлорежисер
actor Користувач
rectangle Software {
  
  Співачка_споживач -- (перегляд можливих варіантів освітлення сцени)
  Співачка_споживач -- (формування Online-замовлення)
  Співачка_споживач -- (пошук на Online-платформах людей)
  Співачка_споживач -- (формування Online-запиту з пропозицією поспілкуватися)
  Співачка_споживач -- (спілкування на тему масової культури)
  Співачка_споживач -- (використання застосунку для співу)
  Співачка_споживач -- (використання спеціального розділу застосунку)

  Світлорежисер -- (підготовка відповідного обладнання)
  
  Світлорежисер -- (відправка макету на пошту)

  Користувач -- (надсилання підтвердження)
  Користувач -- (спілкування на тему масової культури)
  
  
  (перегляд можливих варіантів освітлення сцени) ..> (Авторизувати користувача) : <<include>>

  (формування Online-замовлення) ..> (Авторизувати користувача) : <<include>>
  
  (пошук на Online-платформах людей) ..> (Авторизувати користувача) : <<include>>
  (формування Online-запиту з пропозицією поспілкуватися) ..> (Авторизувати користувача) : <<include>>
  (надсилання підтвердження) ..> (Авторизувати користувача) : <<include>>
  (спілкування на тему масової культури) ..> (Авторизувати користувача) : <<include>>
  
}
@enduml
