@startuml

title Conditional - Activity Diagram 

start

:Користувачка вводить в пошукову строку емоцію, яку переживає зараз;
: Застосунок видає діалогове вікно;

if (Саме ця категорія пісні?) then (Так)
  :Система видає пісню з цієї категорії ;
else (Ні)
  :Система повертається до обирання іншої категорії;
endif

stop

@enduml
