@startuml
title Classes Diagram

Class Користувачка
Class Психологічно_емоційний_стан
Class Пісня
Class Категорія_пісень
Class Онлайн_плеєр

Онлайн_плеєр"*" -up-> "1"Користувачка : надає
Користувачка"*" -up-> "*"Пісня : отримує
Користувачка"*" -up-> "*"Категорія_пісень: отримує
Категорія_пісень"*" --o "1"Онлайн_плеєр : contains
Психологічно_емоційний_стан"*" --o "1"Користувачка : contains
Психологічно_емоційний_стан"*" --o "1"Категорія_пісень : contains
Пісня"*" --o "*"Категорія_пісень : contains

@enduml
